### ISSUE TITLE
comfyui completely breaks after one generation

### ISSUE THREAD

**Issue by DuckersMcQuack** [Yanick112/ComfyUI-ToSVG#3]
It successfully made the SVG, but comfyui is unusable after that one generation.

![chrome_9AZiOcaibD](https://github.com/Yanick112/ComfyUI-ToSVG/assets/9039370/6ac37af0-d140-4d3a-a0b6-58bbcae9992e)

The error. I tried to install the nodes via comfyui manager, but no node pack with those specifics to be found, nor any missing manager could see either.

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-Manager-main\extension-node-map.json [DONE]
[Workflow-Component] '## image-mix-controlnet-seecoder [415367]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "ConditioningAverage " node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-Workflow-Component-Main\workflow_component\component_loader.py", line 202, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-Workflow-Component-Main\workflow_component\component_loader.py", line 350, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "ConditioningAverage " node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## sdxl-ksample [3c7e70]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "Multiply" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-Workflow-Component-Main\workflow_component\component_loader.py", line 202, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-Workflow-Component-Main\workflow_component\component_loader.py", line 350, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "Multiply" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## 2obj [a9bc98]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "Integer" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-Workflow-Component-Main\workflow_component\component_loader.py", line 202, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-Workflow-Component-Main\workflow_component\component_loader.py", line 350, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "Integer" node is not installed. Please install that node through ComfyUI-Mananger. ###

**Comment by Yanick112** [comment]
很抱歉，这么久时间没有回复你，我最近更新了插件你可以再尝试一下。
I'm sorry for the long delay in responding to you. I recently updated the plugin, so you might want to give it another try.
